name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ja, en]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            ${{ matrix.language }}/card_usersmanual.tex
          work_in_root_file_dir: true
          docker_image: texlive/texlive:latest-full
          latexmk_use_lualatex: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: card_usersmanual-${{ matrix.language }}
          path: ${{ matrix.language }}/card_usersmanual.pdf
